# Generated by Django 3.2.5 on 2021-11-21 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20211118_1621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='customer',
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('Cancel', 'Cancel'), ('Accepted', 'Accepted'), ('Packed', 'Packed'), ('Arriving', 'Arriving')], default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('EG', 'Electric Guitar'), ('M', 'Musical'), ('CG', 'Classical Guitar'), ('AG', 'Acoustic Guitar')], max_length=2),
        ),
    ]
